# IP
host-ip: 192.168.0.122
#host-ip: 192.168.0.116
# 公共配置文件
spring:
  application:
    name: yoj-backend-judge-service
  cloud:
    nacos:
      discovery:
        server-addr: ${host-ip}:8848
        ip: ${host-ip}
        port: ${server.port}
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    store-type: redis
    # 30 天过期
    timeout: 2592000
  # Redis 配置
  # todo 需替换配置，然后取消注释
  redis:
    database: 1
    host: ${host-ip}
    port: 6379
    timeout: 5000
    password: 123456
  rabbitmq:
    host: ${host-ip}
    port: 5672
    username: guest
    password: guest
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
server:
  address: 0.0.0.0
  port: 8104
  servlet:
    context-path: /api/judge
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
        path: /api
#代码沙箱配置
codesandbox:
  type: remote
knife4j:
  enable: true
