# IP
host-ip: 192.168.0.116
server:
  address: 0.0.0.0
  port: 8105
  servlet:
    context-path: /api/codesandbox
spring:
  application:
    name: yoj-backend-code-sandbox
  cloud:
    nacos:
      discovery:
        server-addr: ${host-ip}:8848
        ip: ${host-ip}
        port: ${server.port}
knife4j:
  enable: true